version: '3.7'

services:
  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "8000:8000"
      - "8001:8001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":8001"
    volumes:
      - minio-data:/data

volumes:
  minio-data: